WIP: Add wrapper informergen
kcp-dev/code-generator pull request #16
Opened 2022-05-19 20:04 UTC by njhale

Add the `informer` generator to generate kcp-aware wrappers for existing informers.

2022-06-16 22:46 UTC, varshaprasad96 commented on pkg/generators/informergen/gen.go
> +	inputDir string
The generator would run a few additional fields to find the right path to scaffold out the informers. https://github.com/kcp-dev/code-generator/blob/3290e34c024601662f2000893aa03361a5a15121/pkg/generators/clientgen/gen.go#L73-L80, something like this to consider the cases of having apis in subdirectories. If needed, please feel free to move  helpers like [these](https://github.com/kcp-dev/code-generator/blob/3290e34c024601662f2000893aa03361a5a15121/pkg/generators/clientgen/gen.go#L155-L162) out of client-gen.

2022-06-16 22:46 UTC, varshaprasad96 commented on pkg/generators/informergen/gen.go
> +	for _, pkg := range pkgs {
`util.CurrentPacakge` could be helpful here.

2022-06-30 21:47 UTC, fabianvf commented
in getting core types to work I seem to have broken the regular api imports, need to fix that

2022-07-01 19:17 UTC, ncdc requested changes
Can you add copyright headers to all new files that don't have them?

Are any of the new files copied from other repos, or are they all our brand new code?

2022-07-01 19:18 UTC, ncdc commented
/hold

2022-07-01 19:23 UTC, fabianvf commented on examples/go.sum
> +cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
this was an accidental inclusion, will remove

2022-07-01 19:29 UTC, fabianvf commented
> Can you add copyright headers to all new files that don't have them?

:facepalm: yep

> Are any of the new files copied from other repos, or are they all our brand new code?

The templates are _heavily inspired_ by existing informergen but not lifted directly

2022-07-01 21:13 UTC, ncdc commented
/lgtm

2022-07-01 21:13 UTC, ncdc commented
(My force push was just rebasing on top of main and adjusting to namer being moved to third_party. No other changes.)

2022-07-01 21:15 UTC, ncdc commented
/unhold

2022-07-01 21:18 UTC, merged